[package]
name = "markov-chain-music"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
markov = "1.1.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
